name: CICD Pipeline

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ "main" ]

jobs:
  conventional-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3
